- name: Assert is arch
  assert:
    that: ansible_pkg_mgr == 'pacman'
    fail_msg: "i3 setup from this playbook currently only supports archlinux"


- name: Install i3 and related packages
  become: yes
  package:
    name:
      - i3-gaps
      - ttf-font-awesome
      - i3blocks
      - picom
      - rofi
      - dmenu
    state: latest

- name: Install AUR packages
  become: yes
  command: "pikaur -S i3lock-fancy-git --noconfirm"

- name: Create wallpapers directory
  file:
    path: ~/.wallpapers
    state: directory

- name: Download wallpaper
  get_url:
    url: https://unsplash.com/photos/mpWPcRT9D1E/download
    dest: ~/.wallpapers/sunset.jpg

- name: Clone i3blocks contrib
  git:
    repo: https://github.com/vivien/i3blocks-contrib.git
    dest: ~/.i3blocks
    depth: 1

- name: Copy i3 config
  template:
    dest: ~/.config/i3/config
    src: i3config.conf

- name: Copy i3blocks config
  template:
    dest: ~/.config/i3/i3blocks.conf
    src: i3blocks.conf
