---
- name: Create Icons Folder
  file:
    path: ~/.icons
    state: directory
    mode: '0755'

- name: Install Candy Icons
  git:
    repo: https://github.com/EliverLara/candy-icons.git
    dest: ~/.icons/candy-icons
    depth: 1
  when: graphical

- name: Create Themes Folder
  file:
    path: ~/.themes
    state: directory
    mode: '0755'

- name: Install Sweet Dark
  unarchive:
    src: Sweet-Dark.tar.xz
    dest: ~/.themes
