---
- name: Install materia-gtk-theme
  package:
    name: materia-gtk-theme
    state: latest
  become: yes

- name: Add moka PPA
  apt_repository:
    repo: ppa:snwh/ppa
  when: ansible_distribution == 'Ubuntu'

- name: Install moka icons (apt)
  apt:
    name:
      - moka-icon-theme
      - faba-icon-theme
    state: latest
  when: ansible_pkg_mgr == 'apt'
  become: yes

- name: Install moka icons (pikaur)
  become: yes
  command: "pikaur -S moka-icon-theme-git faba-icon-theme-git --noconfirm"
  when: ansible_pkg_mgr == 'pacman'
