---
- name: Copy dconf preferences (debian/ubuntu)
  copy:
    src: "./dconf-settings-deb.ini"
    dest: "{{ tempdir.path }}/dconf-settings.ini"
    mode: 0644
  when: graphical and (ansible_pkg_mgr == 'apt')
  register: dconfd

- name: Copy dconf preferences (arch)
  copy:
    src: "./dconf-settings-arch.ini"
    dest: "{{ tempdir.path }}/dconf-settings.ini"
    mode: 0644
  when: graphical and dconfd is skipped
  register: dconfdarch


- name: Apply dconf preferences
  shell: "dbus-launch dconf load / < {{ tempdir.path }}/dconf-settings.ini"
  when: dconfd

- name: Apply dconf preferences (Arch)
  when: dconfdarch
  shell: "dbus-launch dconf load /org/gnome/ < {{ tempdir.path }}/dconf-settings.ini"
