- name: Create temporary directory
  tempfile:
    state: directory
    suffix: personalization
  register: tempdir

- name: get the username running the deploy
  local_action: command whoami
  register: username_on_the_host

