---
- name: Install ZSH and git(apt)
  become: yes
  apt:
    name:
      - zsh
      - git
    state: latest
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Set Package Install Command(apt)
  set_fact:
    package_install_command: "sudo apt install"
  when: ansible_pkg_mgr == 'apt'

- name: Install ZSH (yum)
  become: yes
  yum:
    name:
      - zsh
      - git
    state: latest
    update_cache: yes
    upgrade: yes
  when: ansible_pkg_mgr == 'yum'

- name: Set Package Install Command(yum)
  set_fact:
    package_install_command: "sudo yum install"
  when: ansible_pkg_mgr == 'yum'

- name: Install ZSH (pacman)
  become: yes
  pacman:
    name:
      - zsh
      - git
    state: latest
  when: ansible_distribution == 'Archlinux'


- name: Set Package Install Command(pacman)
  set_fact:
    package_install_command: "sudo pacman -S"
  when: ansible_distribution == 'Archlinux'

- name: Clone Oh My Zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Clone Powerlevel9k
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
    depth: 1

- name: Clone ZSH autosugestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- name: Clone ZSH syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1

- name: Create ~/.zshrc
  template:
    dest: ~/.zshrc
    src: zsh.rc
