- name: Create ~/.local/bin
  file:
    path: ~/.local/bin
    state: directory
    mode: '0755'

- name: Copy ipa script
  copy:
    src: ipa.py
    dest: ~/.local/bin/ipa
    mode: '0755'

- name: Copy simplehttp script
  copy:
    src: simplehttp.py
    dest: ~/.local/bin/simplehttp
    mode: '0755'
