# Install nano
- name: Install nano(apt)
  apt:
    name: nano
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: yes

- name: Install nano (yum)
  yum:
    name: nano
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  become: yes

- name: Install nano (pacman)
  pacman:
    name: nano
    state: latest
  when: ansible_distribution == 'Archlinux'
  become: yes

- name: Clone nanorc repo
  git:
    repo: https://github.com/scopatz/nanorc.git
    dest: ~/.nano
    depth: 1

- name: Copy ~/.nanorc
  copy:
    src: ./nanorc
    dest: ~/.nanorc
    mode: 0644
