# Install nano
- name: Install nano(apt)
  apt:
    name: nano
    state: latest
  when: ansible_pkg_mgr == 'apt'
  become: yes

- name: Install nano (yum)
  yum:
    name: nano
    state: latest
  when: ansible_pkg_mgr == 'yum'
  become: yes

- name: Install nano (pacman)
  pacman:
    name: nano
    state: latest
  when: ansible_pkg_mgr == 'pacman'
  become: yes

- name: Clone nanorc repo
  git:
    repo: https://github.com/scopatz/nanorc.git
    dest: ~/.nano
    depth: 1

- name: Copy ~/.nanorc
  copy:
    src: ./nanorc
    dest: ~/.nanorc
    mode: 0644
