- name: Clone pikaur from git (AUR manager)
  git:
    repo: "https://aur.archlinux.org/pikaur.git"
    dest: "{{ tempdir.path }}/pikaur"

- name: Create Pikaur Config File
  copy:
    src: "pikaur.conf"
    dest: "~/.config/pikaur.conf"

#- name: Install pikaur
#  command: "makepkg -fsri --noconfirm"
#  args:
#    chdir: "{{ tempdir.path }}/pikaur"

- name: Install AUR packages
  become: yes
  command: "pikaur -S {{aur_packages | join(' ')}} --noconfirm"
